export const estilosAdmin = {
    card: 'rounded-3xl border border-cyan-500/20 bg-gradient-to-br from-slate-900 via-slate-900 to-cyan-950/30 p-6 shadow-[0_0_30px_rgba(34,211,238,0.12)] transition-colors theme-light:border-slate-300 theme-light:bg-none theme-light:bg-white theme-light:shadow-slate-200',
    cardBlue: 'border-t-[3px] border-t-[#00ccff]',
    cardTeal: 'border-t-[3px] border-t-[#00f5e0]',
    cardHeader: 'mb-5 flex flex-col items-start gap-4 sm:flex-row sm:items-center',
    icon: 'flex size-14 shrink-0 items-center justify-center rounded-xl bg-cyan-400/10 text-2xl text-cyan-300',
    iconTeal: 'bg-teal-300/10 text-teal-300',
    sectionTitle: 'text-lg font-bold text-white theme-light:text-slate-900',
    sectionDescription: 'mt-1 text-sm leading-relaxed text-slate-400 theme-light:text-slate-600',
    form: 'flex w-full flex-col gap-4',
    fieldset: 'min-w-0 border-0 p-0',
    legend: 'mb-2 block text-xs font-bold uppercase tracking-wider text-cyan-300',
    input: 'w-full rounded-lg border border-[#2a3550] bg-[#0d1117] px-3.5 py-3 text-sm text-white outline-none transition placeholder:text-slate-500 focus:border-cyan-400 focus:ring-2 focus:ring-cyan-400/20 theme-light:border-slate-300 theme-light:bg-white theme-light:text-slate-900',
    button: 'inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border px-4 py-2.5 text-sm font-semibold transition hover:-translate-y-px focus-visible:outline-2 focus-visible:outline-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
    primaryButton: 'border-cyan-400/40 bg-cyan-400/10 text-cyan-300 hover:border-cyan-300 hover:bg-cyan-400 hover:text-slate-950 focus-visible:outline-cyan-400 theme-light:border-blue-700/30 theme-light:bg-blue-700/10 theme-light:text-blue-800 theme-light:hover:bg-blue-700 theme-light:hover:text-white',
    secondaryButton: 'border-[#2a3550] bg-white/5 text-slate-300 hover:border-slate-400 hover:bg-white/10 hover:text-white focus-visible:outline-slate-400 theme-light:border-slate-300 theme-light:bg-slate-100 theme-light:text-slate-700 theme-light:hover:bg-slate-200 theme-light:hover:text-slate-900',
    dangerButton: 'border-red-400/30 bg-red-400/5 text-red-300 hover:border-red-400 hover:bg-red-500 hover:text-white focus-visible:outline-red-400',
    list: 'mt-3 flex w-full list-none flex-col gap-2.5 p-0',
    listItem: 'flex flex-col gap-4 rounded-lg border border-[#1a2030] bg-[#0a0f1c] p-4 transition hover:border-[#2a3550] sm:flex-row sm:items-center sm:justify-between theme-light:border-slate-300 theme-light:bg-slate-50',
    muted: 'text-sm text-slate-400 theme-light:text-slate-600',
    empty: 'flex flex-col items-center gap-3 py-8 text-center text-sm text-slate-400 theme-light:text-slate-600',
};
